// Tailwind config that scans all client source files.
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: "#b02f00",
        "primary-container": "#ff5722",
        "on-primary-container": "#541200",
        secondary: "#b7131a",
        "secondary-container": "#db322f",
        "on-secondary-container": "#fffbff",
        tertiary: "#5c5c5c",
        "tertiary-container": "#757474",
        "on-tertiary": "#ffffff",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        surface: "#f9f9f9",
        "on-surface": "#1a1c1c",
        "surface-variant": "#e2e2e2",
        "on-surface-variant": "#5b4039",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-tint": "#b02f00",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        outline: "#907067",
        "outline-variant": "#e4beb4",
        "inverse-primary": "#ffb5a0",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
      },
      fontFamily: {
        headline: ["Anybody", "sans-serif"],
        sans: ["DM Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
