import { useState } from 'react';
import { useSocket } from './useSocket.js';
import { useLanguage } from '../context/LanguageContext.jsx';
import { useGameActions } from './useGameActions.js';
import { useGameInteractions } from './useGameInteractions.js';
import { useRoomSync } from './useRoomSync.js';

export const USE_GAME_RETURN_KEYS = [
  'socket',
  'connectionState',
  'roomState',
  'setRoomState',
  'gameState',
  'privateHand',
  'nopeWindow',
  'nopeResult',
  'nowCardToast',
  'seeTheFutureCards',
  'setSeeTheFutureCards',
  'activeInteractionRequest',
  'alterFutureRequest',
  'favorRequest',
  'buryRequest',
  'garbageRequest',
  'potLuckRequest',
  'zombieRequest',
  'defuseRequest',
  'selectTargetRequest',
  'feedTheDeadRequest',
  'graveRobberRequest',
  'digDeeperRequest',
  'armageddonRequest',
  'clairvoyanceReveal',
  'gameEnded',
  'setGameEnded',
  'chatMessages',
  'statusMessage',
  'setStatusMessage',
  'actionLog',
  'createRoom',
  'joinRoom',
  'leaveRoom',
  'startGame',
  'toggleReady',
  'updateRoomSettings',
  'kickPlayer',
  'drawCard',
  'playCard',
  'playNope',
  'passNope',
  'discardCard',
  'respondFavor',
  'respondAlterFuture',
  'respondBury',
  'respondGarbage',
  'respondPotLuck',
  'respondZombie',
  'respondDefuse',
  'respondSelectTarget',
  'respondFeedTheDead',
  'respondGraveRobber',
  'respondDigDeeper',
  'respondArmageddonDistribute',
  'respondArmageddonDecision',
  'playCombo',
  'respondCombo5',
  'sendChatMessage',
  'sendEmote',
  'playAgain',
];

export function useGame() {
  const socket = useSocket();
  const { t } = useLanguage();
  const [statusMessage, setStatusMessage] = useState('');

  const interactions = useGameInteractions({ socket, t, setStatusMessage });
  const roomSync = useRoomSync({
    socket,
    t,
    setStatusMessage,
    clearResolvedInteractions: interactions.clearResolvedInteractions,
    setNowCardToast: interactions.setNowCardToast,
  });

  const actions = useGameActions({
    socket,
    roomState: roomSync.roomState,
    activeInteractionRequest: interactions.activeInteractionRequest,
    setRoomState: roomSync.setRoomState,
    setGameState: roomSync.setGameState,
    setPrivateHand: roomSync.setPrivateHand,
    setGameEnded: roomSync.setGameEnded,
    setActionLog: roomSync.setActionLog,
    setNopeWindow: interactions.setNopeWindow,
    setFavorRequest: interactions.setFavorRequest,
    setAlterFutureRequest: interactions.setAlterFutureRequest,
    setBuryRequest: interactions.setBuryRequest,
    setGarbageRequest: interactions.setGarbageRequest,
    setPotLuckRequest: interactions.setPotLuckRequest,
    setZombieRequest: interactions.setZombieRequest,
    setDefuseRequest: interactions.setDefuseRequest,
    setSelectTargetRequest: interactions.setSelectTargetRequest,
    setFeedTheDeadRequest: interactions.setFeedTheDeadRequest,
    setGraveRobberRequest: interactions.setGraveRobberRequest,
    setDigDeeperRequest: interactions.setDigDeeperRequest,
    setArmageddonRequest: interactions.setArmageddonRequest,
  });

  return {
    socket,
    connectionState: roomSync.connectionState,
    roomState: roomSync.roomState,
    setRoomState: roomSync.setRoomState,
    gameState: roomSync.gameState,
    privateHand: roomSync.privateHand,
    nopeWindow: interactions.nopeWindow,
    nopeResult: interactions.nopeResult,
    nowCardToast: interactions.nowCardToast,
    seeTheFutureCards: interactions.seeTheFutureCards,
    setSeeTheFutureCards: interactions.setSeeTheFutureCards,
    activeInteractionRequest: interactions.activeInteractionRequest,
    alterFutureRequest: interactions.alterFutureRequest,
    favorRequest: interactions.favorRequest,
    buryRequest: interactions.buryRequest,
    garbageRequest: interactions.garbageRequest,
    potLuckRequest: interactions.potLuckRequest,
    zombieRequest: interactions.zombieRequest,
    defuseRequest: interactions.defuseRequest,
    selectTargetRequest: interactions.selectTargetRequest,
    feedTheDeadRequest: interactions.feedTheDeadRequest,
    graveRobberRequest: interactions.graveRobberRequest,
    digDeeperRequest: interactions.digDeeperRequest,
    armageddonRequest: interactions.armageddonRequest,
    clairvoyanceReveal: interactions.clairvoyanceReveal,
    gameEnded: roomSync.gameEnded,
    setGameEnded: roomSync.setGameEnded,
    chatMessages: roomSync.chatMessages,
    statusMessage,
    setStatusMessage,
    actionLog: roomSync.actionLog,
    ...actions,
  };
}
