export const VFX_CARD_TYPES = [
  'ATTACK', 'ATTACK_2X', 'TARGET_ATTACK', 'TARGET_ATTACK_2X', 'PERSONAL_ATTACK',
  'SKIP', 'SUPER_SKIP', 'REVERSE',
  'SHUFFLE', 'SHUFFLE_NOW', 'NOPE',
  'SEE_THE_FUTURE_1', 'SEE_THE_FUTURE_3', 'SEE_THE_FUTURE_5',
  'SEE_THE_FUTURE_3X', 'SEE_THE_FUTURE_5X', 'SEE_THE_FUTURE_3_AND_SHARE',
  'ALTER_THE_FUTURE_3', 'ALTER_THE_FUTURE_3X', 'ALTER_THE_FUTURE_5',
  'FAVOR', 'I_LL_TAKE_THAT',
  'DRAW_FROM_BOTTOM', 'DRAW_FROM_THE_BOTTOM', 'DRAW_BOTTOM',
  'NORMAL_CAT', 'CAT_TACO', 'CAT_WATERMELON', 'CAT_BEARD', 'CAT_RAINBOW', 'CAT_POTATO',
  'FERAL_CAT', 'GODCAT',
  'BURY', 'POT_LUCK', 'POTLUCK', 'GARBAGE_COLLECTION', 'MARK',
  'ZOMBIE_KITTEN', 'ATTACK_OF_THE_DEAD', 'FEED_THE_DEAD', 'GRAVE_ROBBER', 'DIG_DEEPER',
  'GENERIC',
];

export const VFX_ATTACK_KEYS = [
  'CARD_ATTACK',
  'CARD_ATTACK_2X',
  'CARD_TARGET_ATTACK',
  'CARD_TARGET_ATTACK_2X',
  'CARD_PERSONAL_ATTACK',
  'CARD_ATTACK_OF_THE_DEAD',
];

export const REQUIRED_VFX_KEYS = [
  'CARD_SKIP',
  'CARD_REVERSE',
  'CARD_NOPE',
  'CARD_ATTACK',
  'CARD_SHUFFLE',
  'CARD_EXPLODING_KITTEN',
  'CARD_DEFUSE',
  'ENV_TURN_HIGHLIGHT',
];
